// Code generated by protoc-gen-go.
// source: hyperledgerREST.proto
// DO NOT EDIT!

/*
Package beans is a generated protocol buffer package.

It is generated from these files:
	hyperledgerREST.proto
	punchclock.proto
	redis.proto
	sendMail.proto

It has these top-level messages:
	GetEmployee
	GetPunchclock
	APIError
	TimeStruct
	Punchclock
	EmployeeOnChain
	PunchclockOnChain
	DailyPunchclockData
	Redis
	SendMail
*/
package beans

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetEmployee struct {
	Class     string    `protobuf:"bytes,1,opt,name=Class"         json:"$class"       form:"$class"`
	Identify  string    `protobuf:"bytes,2,opt,name=Identify"      json:"identify"     form:"identify"`
	FirstName string    `protobuf:"bytes,3,opt,name=FirstName"     json:"firstName"    form:"firstName"`
	LastName  string    `protobuf:"bytes,4,opt,name=LastName"      json:"lastName"     form:"lastName"`
	Error     *APIError `protobuf:"bytes,5,opt,name=Error"         json:"error"        form:"error"`
}

func (m *GetEmployee) Reset()                    { *m = GetEmployee{} }
func (m *GetEmployee) String() string            { return proto.CompactTextString(m) }
func (*GetEmployee) ProtoMessage()               {}
func (*GetEmployee) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetEmployee) GetClass() string {
	if m != nil {
		return m.Class
	}
	return ""
}

func (m *GetEmployee) GetIdentify() string {
	if m != nil {
		return m.Identify
	}
	return ""
}

func (m *GetEmployee) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *GetEmployee) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *GetEmployee) GetError() *APIError {
	if m != nil {
		return m.Error
	}
	return nil
}

type GetPunchclock struct {
	Class       string    `protobuf:"bytes,12,opt,name=Class"        json:"$class"       form:"$class"`
	ID          string    `protobuf:"bytes,13,opt,name=ID"           json:"id"           form:"id"`
	OnWorkDate  string    `protobuf:"bytes,14,opt,name=OnWorkDate"   json:"onWorkDate"   form:"onWorkDate"`
	OffWorkTime string    `protobuf:"bytes,15,opt,name=OffWorkTime"  json:"offWorkTime"  form:"offWorkTime"`
	WorkTimes   string    `protobuf:"bytes,16,opt,name=WorkTimes"    json:"workTimes"    form:"workTimes"`
	Employee    string    `protobuf:"bytes,17,opt,name=Employee"     json:"employee"     form:"employee"`
	Error       *APIError `protobuf:"bytes,18,opt,name=Error"        json:"error"        form:"error"`
}

func (m *GetPunchclock) Reset()                    { *m = GetPunchclock{} }
func (m *GetPunchclock) String() string            { return proto.CompactTextString(m) }
func (*GetPunchclock) ProtoMessage()               {}
func (*GetPunchclock) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetPunchclock) GetClass() string {
	if m != nil {
		return m.Class
	}
	return ""
}

func (m *GetPunchclock) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *GetPunchclock) GetOnWorkDate() string {
	if m != nil {
		return m.OnWorkDate
	}
	return ""
}

func (m *GetPunchclock) GetOffWorkTime() string {
	if m != nil {
		return m.OffWorkTime
	}
	return ""
}

func (m *GetPunchclock) GetWorkTimes() string {
	if m != nil {
		return m.WorkTimes
	}
	return ""
}

func (m *GetPunchclock) GetEmployee() string {
	if m != nil {
		return m.Employee
	}
	return ""
}

func (m *GetPunchclock) GetError() *APIError {
	if m != nil {
		return m.Error
	}
	return nil
}

type APIError struct {
	StatusCode int32  ` protobuf:"varint,6,opt,name=statusCode"   json:"statusCode,omitempty"`
	Name       string ` protobuf:"bytes,7,opt,name=name"          json:"name,omitempty"`
	Message    string ` protobuf:"bytes,8,opt,name=message"       json:"message,omitempty"`
	Status     string ` protobuf:"bytes,9,opt,name=status"        json:"status,omitempty"`
	Code       string ` protobuf:"bytes,10,opt,name=code"         json:"code,omitempty"`
	Stack      string ` protobuf:"bytes,11,opt,name=stack"        json:"stack,omitempty"`
}

func (m *APIError) Reset()                    { *m = APIError{} }
func (m *APIError) String() string            { return proto.CompactTextString(m) }
func (*APIError) ProtoMessage()               {}
func (*APIError) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *APIError) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *APIError) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *APIError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *APIError) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *APIError) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *APIError) GetStack() string {
	if m != nil {
		return m.Stack
	}
	return ""
}

func init() {
	proto.RegisterType((*GetEmployee)(nil), "beans.GetEmployee")
	proto.RegisterType((*GetPunchclock)(nil), "beans.GetPunchclock")
	proto.RegisterType((*APIError)(nil), "beans.APIError")
}

func init() { proto.RegisterFile("hyperledgerREST.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xdf, 0x6a, 0xea, 0x40,
	0x10, 0xc6, 0x89, 0xc7, 0xf8, 0x67, 0x72, 0xd4, 0x73, 0x96, 0xb6, 0x0c, 0xa5, 0x94, 0x20, 0x14,
	0xbc, 0xf2, 0xa2, 0x7d, 0x82, 0xa2, 0x56, 0x02, 0xa5, 0x4a, 0x2a, 0xf4, 0x7a, 0x8d, 0xe3, 0x1f,
	0x4c, 0xb2, 0xb2, 0xbb, 0x5e, 0xf8, 0x2a, 0xbd, 0xea, 0x63, 0xf5, 0x71, 0xca, 0xee, 0x9a, 0x98,
	0xab, 0xde, 0xcd, 0xf7, 0x9b, 0xcc, 0x64, 0xbe, 0x8f, 0x85, 0xeb, 0xed, 0xe9, 0x40, 0x32, 0xa5,
	0xd5, 0x86, 0x64, 0x3c, 0x79, 0x5f, 0x0c, 0x0f, 0x52, 0x68, 0xc1, 0xfc, 0x25, 0xf1, 0x5c, 0xf5,
	0xbf, 0x3c, 0x08, 0xa6, 0xa4, 0x27, 0xd9, 0x21, 0x15, 0x27, 0x22, 0x76, 0x05, 0xfe, 0x28, 0xe5,
	0x4a, 0xa1, 0x17, 0x7a, 0x83, 0x76, 0xec, 0x04, 0xbb, 0x85, 0x56, 0xb4, 0xa2, 0x5c, 0xef, 0xd6,
	0x27, 0xac, 0xd9, 0x46, 0xa9, 0xd9, 0x1d, 0xb4, 0x5f, 0x76, 0x52, 0xe9, 0x37, 0x9e, 0x11, 0xfe,
	0xb1, 0xcd, 0x0b, 0x30, 0x93, 0xaf, 0xfc, 0xdc, 0xac, 0xbb, 0xc9, 0x42, 0xb3, 0x07, 0xf0, 0x27,
	0x52, 0x0a, 0x89, 0x7e, 0xe8, 0x0d, 0x82, 0xc7, 0xde, 0xd0, 0x9e, 0x34, 0x7c, 0x9e, 0x47, 0x16,
	0xc7, 0xae, 0xdb, 0xff, 0xf6, 0xa0, 0x33, 0x25, 0x3d, 0x3f, 0xe6, 0xc9, 0x36, 0x49, 0x45, 0xb2,
	0xbf, 0x1c, 0xf9, 0xb7, 0x7a, 0x64, 0x17, 0x6a, 0xd1, 0x18, 0x3b, 0x16, 0xd5, 0xa2, 0x31, 0xbb,
	0x07, 0x98, 0xe5, 0x1f, 0x42, 0xee, 0xc7, 0x5c, 0x13, 0x76, 0x2d, 0xaf, 0x10, 0x16, 0x42, 0x30,
	0x5b, 0xaf, 0x8d, 0x5c, 0xec, 0x32, 0xc2, 0x9e, 0xfd, 0xa0, 0x8a, 0x8c, 0xb5, 0xa2, 0x56, 0xf8,
	0xcf, 0x59, 0x2b, 0x81, 0xb1, 0x56, 0xc4, 0x86, 0xff, 0x9d, 0xb5, 0x32, 0xc6, 0xd2, 0x1a, 0xfb,
	0xd5, 0xda, 0xa7, 0x07, 0xad, 0x82, 0x99, 0x7b, 0x95, 0xe6, 0xfa, 0xa8, 0x46, 0x62, 0x45, 0xd8,
	0x08, 0xbd, 0x81, 0x1f, 0x57, 0x08, 0x63, 0x50, 0xcf, 0x4d, 0x8c, 0x4d, 0xfb, 0x2f, 0x5b, 0x33,
	0x84, 0x66, 0x46, 0x4a, 0xf1, 0x0d, 0x61, 0xcb, 0xe2, 0x42, 0xb2, 0x1b, 0x68, 0xb8, 0x59, 0x6c,
	0xdb, 0xc6, 0x59, 0x99, 0x2d, 0x89, 0xd9, 0x0f, 0x6e, 0x8b, 0xa9, 0x4d, 0x9e, 0x4a, 0xf3, 0x64,
	0x8f, 0x81, 0xcb, 0xd3, 0x8a, 0x65, 0xc3, 0x3e, 0x94, 0xa7, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xce, 0xc4, 0x57, 0xe3, 0x41, 0x02, 0x00, 0x00,
}
