// Code generated by protoc-gen-go.
// source: redis.proto
// DO NOT EDIT!

/*
Package beans is a generated protocol buffer package.

It is generated from these files:
	redis.proto
	sendMail.proto

It has these top-level messages:
	Redis
	SendMail
*/
package beans

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Redis struct {
	Key      string `protobuf:"bytes,1,opt,name=Key"        json:"key,omitempty"`
	Value    string `protobuf:"bytes,2,opt,name=Value"      json:"value,omitempty"`
	Interval int64  `protobuf:"varint,3,opt,name=Interval"  json:"interval,omitempty"`
	Hkey     string `protobuf:"bytes,4,opt,name=Hkey"       json:"hkey,omitempty"`
}

func (m *Redis) Reset()                    { *m = Redis{} }
func (m *Redis) String() string            { return proto.CompactTextString(m) }
func (*Redis) ProtoMessage()               {}
func (*Redis) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Redis) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Redis) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Redis) GetInterval() int64 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *Redis) GetHkey() string {
	if m != nil {
		return m.Hkey
	}
	return ""
}

func init() {
	proto.RegisterType((*Redis)(nil), "beans.Redis")
}

func init() { proto.RegisterFile("redis.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 121 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x4a, 0x4d, 0xc9,
	0x2c, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4d, 0x4a, 0x4d, 0xcc, 0x2b, 0x56, 0x8a,
	0xe7, 0x62, 0x0d, 0x02, 0x89, 0x0a, 0x09, 0x70, 0x31, 0x7b, 0xa7, 0x56, 0x4a, 0x30, 0x2a, 0x30,
	0x6a, 0x70, 0x06, 0x81, 0x98, 0x42, 0x22, 0x5c, 0xac, 0x61, 0x89, 0x39, 0xa5, 0xa9, 0x12, 0x4c,
	0x60, 0x31, 0x08, 0x47, 0x48, 0x8a, 0x8b, 0xc3, 0x33, 0xaf, 0x24, 0xb5, 0xa8, 0x2c, 0x31, 0x47,
	0x82, 0x59, 0x81, 0x51, 0x83, 0x39, 0x08, 0xce, 0x17, 0x12, 0xe2, 0x62, 0xf1, 0xc8, 0x4e, 0xad,
	0x94, 0x60, 0x01, 0x6b, 0x00, 0xb3, 0x93, 0xd8, 0xc0, 0xd6, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x98, 0x98, 0x85, 0x61, 0x7d, 0x00, 0x00, 0x00,
}
